import json

from okta.util.exceptions import (
    DecodeError, ExpiredTokenError, ImmatureSignatureError,
    InvalidAudienceError, InvalidIssuedAtError,
    InvalidIssuerError, MissingRequiredClaimError
)
from okta.util.jwt import JwtVerifier

# this is a valid, signed JWT
jwt = "eyJraWQiOiJFQ3JNSEptd1I4SXZFVTY5RTNtNmF0OTAyQzZzR0FGeFUzSGJ5MzRKUl9jIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmJQYUxEWllIWWtGT29rTGlXZFJZek1VWHVnV2ZzR1VmaHp2UFhwX1B3RGciLCJpc3MiOiJodHRwczovL3dhbGxpY2sub2t0YXByZXZpZXcuY29tL29hdXRoMi9hdXNqdGI2OXJ6a3N3VlBDUTBoNyIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE1NTM4OTM2MzMsImV4cCI6MTU1Mzg5NzIzMywiY2lkIjoiMG9hanRhZTI1MkpndVZnWG4waDciLCJ1aWQiOiIwMHVlaHhqYmoxQXI5Qnp4bjBoNyIsInNjcCI6WyJvcGVuaWQiLCJlbWFpbCIsInByb2ZpbGUiXSwic3ViIjoibGVzLmNsYXlwb29sQG1haWxpbmF0b3IuY29tIn0.EadWhSOvVrj8ydjXEQQ58gX4fLejA0_AB8H9T_jR-WIYAYhhnyrsL0FYo-k0OE8b6xet4wko-1iF3u7cqYpJbdCepZNIosIy7Bruh-FC2pPNH4CJ-FAJ5W5FmuBUT4mShwiETdrimtl-BXBY0NAkwsOIdKzJz0H7Jcvh7x4rR4esYSxvVE-LpJDweNXLzXsjEHFp42Hpcb6oS6C5u3r5BNR6er4t9wXA9EB_Iaex64uKua02GkF8PBSazYbVDx_HalI7v1B5A1EVfT-qbs2S888o0khpf1smpbYy4-CAjEFfSxl2MGmKZU_nCqxHK_0Ml77O0d2RZJZ3EtJK4QZIgg"

# this JWT has been tampered with to extend the exp time
# it fails signature validation
#jwt = "eyJraWQiOiJFQ3JNSEptd1I4SXZFVTY5RTNtNmF0OTAyQzZzR0FGeFUzSGJ5MzRKUl9jIiwiYWxnIjoiUlMyNTYifQ.ewogICAgImF1ZCI6ICJhcGk6Ly9kZWZhdWx0IiwKICAgICJjaWQiOiAiMG9hanRhZTI1MkpndVZnWG4waDciLAogICAgImV4cCI6IDE1NTM4OTEzNjMsCiAgICAiaWF0IjogMTU1Mzc4Nzc2MywKICAgICJpc3MiOiAiaHR0cHM6Ly93YWxsaWNrLm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzanRiNjlyemtzd1ZQQ1EwaDciLAogICAgImp0aSI6ICJBVC5BUTkwZzBpRkRLaWRDNVRVSUxSYmtjc21RcHhOSjd0TXRNMGJtWXNudVFFIiwKICAgICJzY3AiOiBbCiAgICAgICAgInByb2ZpbGUiLAogICAgICAgICJlbWFpbCIsCiAgICAgICAgIm9wZW5pZCIKICAgIF0sCiAgICAic3ViIjogImxlcy5jbGF5cG9vbEBtYWlsaW5hdG9yLmNvbSIsCiAgICAidWlkIjogIjAwdWVoeGpiajFBcjlCenhuMGg3IiwKICAgICJ2ZXIiOiAxCn0=.Z_Bqr9SAamny8Ky-Qh2dovUz-5udzRyh0FzDi2crGewFdo94oxmigqD5YnbKlxZKtBdJxL2RYaAoPcIbCaeX4JEPg8Mv2EogUQ-L_04WvVCyaNBYhvJm6oMOnf4yKniDNZN-0bRAFJ4Cl5jQFvQ9iTvhBZKyEt9hJD_N_h7kw2AH1TwwMkd6VIsLPTH99qEPhJBalahfDlsFfcpsldOjUyS0sIw_8e5NqE5C3OJ5v6QBqeHshda1oTzqISUtIHEtx3Fdh0G8KDmnSr8dW75WjRrtVgsty6BuCZzhjROfsIluvbC7agNsZ7tXcKg5fupeYQDnqJtXkImA6UsZed0Rnw"

try:
    okta = JwtVerifier()
    decoded_jwt = okta.decode(jwt)
    print("decoded_jwt: {0}".format(json.dumps(decoded_jwt, indent=4, sort_keys=True)))
except ExpiredTokenError:
    print("JWT signature is valid, but the token has expired. Please re-authenticate")
